<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use App\Models\School;

class NegaraSembilanSchoolSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Reset auto-increment to start from ID 3 if no schools exist yet
        $schoolCount = School::count();
        if ($schoolCount <= 2) {
            DB::statement('ALTER TABLE schools AUTO_INCREMENT = 3');
        }

        $schools = [
            [
                'name' => 'SMK DATO\' UNDANG MUSA AL-HAJ',
                'address' => 'KM 2, JALAN PERTANG, KUALA KLAWANG, JELEBU 71600',
                'phone' => '066136225',
                'email' => null,
                'type' => 'public',
                'total_students' => null,
                'teacher_name' => null,
                'teacher_email' => null,
                'status' => 'inactive',
            ],
            [
                'name' => 'SMK DATO\' UNDANG SYED ALI AL-JUFRI',
                'address' => 'SIMPANG GELAMI BT 4 1/2 PERADONG SIMPANG GELAMI KUALA KLAWANG 71600',
                'phone' => '066136895',
                'email' => null,
                'type' => 'public',
                'total_students' => null,
                'teacher_name' => null,
                'teacher_email' => null,
                'status' => 'inactive',
            ],
            [
                'name' => 'SMK BAHAU',
                'address' => 'KM 3, JALAN ROMPIN BAHAU 72100',
                'phone' => '064541232',
                'email' => null,
                'type' => 'public',
                'total_students' => null,
                'teacher_name' => null,
                'teacher_email' => null,
                'status' => 'inactive',
            ],
            [
                'name' => 'SMK (FELDA) PASOH 2',
                'address' => 'FELDA PASOH 2 SIMPANG PERTANG 72300',
                'phone' => '064961185',
                'email' => null,
                'type' => 'public',
                'total_students' => null,
                'teacher_name' => null,
                'teacher_email' => null,
                'status' => 'inactive',
            ],
            [
                'name' => 'SMK SERI PERPATIH PUSAT BANDAR PALONG 4,5 & 6',
                'address' => 'GEMAS 73430',
                'phone' => '064666362',
                'email' => null,
                'type' => 'public',
                'total_students' => null,
                'teacher_name' => null,
                'teacher_email' => null,
                'status' => 'inactive',
            ],
            [
                'name' => 'SMK (FELDA) PALONG DUA',
                'address' => 'FELDA PALONG 2 GEMAS 73450',
                'phone' => '064631314',
                'email' => null,
                'type' => 'public',
                'total_students' => null,
                'teacher_name' => null,
                'teacher_email' => null,
                'status' => 'inactive',
            ],
            [
                'name' => 'SMK (FELDA) LUI BARAT',
                'address' => 'BANDAR SERI JEMPOL 72120',
                'phone' => '064676300',
                'email' => null,
                'type' => 'public',
                'total_students' => null,
                'teacher_name' => null,
                'teacher_email' => null,
                'status' => 'inactive',
            ],
            [
                'name' => 'SMK (FELDA) PALONG 7',
                'address' => 'FELDA PALONG TUJUH GEMAS 73470',
                'phone' => '064645464',
                'email' => null,
                'type' => 'public',
                'total_students' => null,
                'teacher_name' => null,
                'teacher_email' => null,
                'status' => 'inactive',
            ],
            [
                'name' => 'SMK (FELDA) BANDAR BARU SERTING',
                'address' => 'BANDAR SERI JEMPOL 72120',
                'phone' => '064581849',
                'email' => null,
                'type' => 'public',
                'total_students' => null,
                'teacher_name' => null,
                'teacher_email' => null,
                'status' => 'inactive',
            ],
            [
                'name' => 'SMK SERTING HILIR',
                'address' => 'KOMPLEKS FELDA SERTING HILIR 4 BANDAR SERI JEMPOL 72120',
                'phone' => '064684504',
                'email' => null,
                'type' => 'public',
                'total_students' => null,
                'teacher_name' => null,
                'teacher_email' => null,
                'status' => 'inactive',
            ],
            [
                'name' => 'SMK PALONG SEBELAS (FELDA)',
                'address' => 'FELDA PALONG SEBELAS GEMAS 73430',
                'phone' => '064669751',
                'email' => null,
                'type' => 'public',
                'total_students' => null,
                'teacher_name' => null,
                'teacher_email' => null,
                'status' => 'inactive',
            ],
            [
                'name' => 'SMK SERI JEMPOL',
                'address' => 'BANDAR SERI JEMPOL 72120',
                'phone' => '064584061',
                'email' => null,
                'type' => 'public',
                'total_students' => null,
                'teacher_name' => null,
                'teacher_email' => null,
                'status' => 'inactive',
            ],
            [
                'name' => 'SMK BAHAU 2',
                'address' => 'PEKAN MAHSAN, BAHAU 72100',
                'phone' => '064540084',
                'email' => null,
                'type' => 'public',
                'total_students' => null,
                'teacher_name' => null,
                'teacher_email' => null,
                'status' => 'inactive',
            ],
            [
                'name' => 'SMK UNDANG JELEBU',
                'address' => 'KM3 JALAN PETALING KUALA KLAWANG 71600',
                'phone' => '066136202',
                'email' => null,
                'type' => 'public',
                'total_students' => null,
                'teacher_name' => null,
                'teacher_email' => null,
                'status' => 'inactive',
            ],
            [
                'name' => 'SMK PERTANG',
                'address' => 'KM 1, JALAN GELANG SIMPANG PERTANG 72300',
                'phone' => '064941444',
                'email' => null,
                'type' => 'public',
                'total_students' => null,
                'teacher_name' => null,
                'teacher_email' => null,
                'status' => 'inactive',
            ],
            [
                'name' => 'SMK CHI WEN (CF)',
                'address' => 'JALAN RAJA MUDA SERTING BAHAU 72100',
                'phone' => '064541278',
                'email' => null,
                'type' => 'private',
                'total_students' => null,
                'teacher_name' => null,
                'teacher_email' => null,
                'status' => 'inactive',
            ],
            [
                'name' => 'SMK TERIANG HILIR',
                'address' => 'KM 1 JALAN SUNGAI BULOH SIMPANG DURIAN 72400',
                'phone' => '064914411',
                'email' => null,
                'type' => 'public',
                'total_students' => null,
                'teacher_name' => null,
                'teacher_email' => null,
                'status' => 'inactive',
            ],
            [
                'name' => 'SMK DATUK MANSOR',
                'address' => 'KM4, JALAN JUASSEH, BAHAU 72100',
                'phone' => '064541121',
                'email' => null,
                'type' => 'public',
                'total_students' => null,
                'teacher_name' => null,
                'teacher_email' => null,
                'status' => 'inactive',
            ],
            [
                'name' => 'SMK BATU KIKIR',
                'address' => 'BATU KIKIR 72200',
                'phone' => '064981393',
                'email' => null,
                'type' => 'public',
                'total_students' => null,
                'teacher_name' => null,
                'teacher_email' => null,
                'status' => 'inactive',
            ],
            [
                'name' => 'SM RENDAH AGAMA KUALA KLAWANG',
                'address' => 'JLN MASJID LAMA KUALA KLAWANG 71600',
                'phone' => '066138523',
                'email' => null,
                'type' => 'public',
                'total_students' => null,
                'teacher_name' => null,
                'teacher_email' => null,
                'status' => 'inactive',
            ],
            [
                'name' => 'SM AGAMA DATO\' HAJI TAN AHMAD',
                'address' => 'KAMPUNG SIMPANG DURIAN 72400',
                'phone' => '064914680',
                'email' => null,
                'type' => 'public',
                'total_students' => null,
                'teacher_name' => null,
                'teacher_email' => null,
                'status' => 'inactive',
            ],
            [
                'name' => 'SEKOLAH MENENGAH AGAMA HAJI MUHAMAD',
                'address' => 'LOT 3222 KAMPUNG JAMBU LAPAN BAHAU 72100',
                'phone' => '064545432',
                'email' => null,
                'type' => 'public',
                'total_students' => null,
                'teacher_name' => null,
                'teacher_email' => null,
                'status' => 'inactive',
            ],
            // Additional JEMPOL/JELEBU schools
            [
                'name' => 'SM AGAMA DATO\' HAJI MUSTAFA',
                'address' => 'LOT 6348 BATU KIKIR 72200',
                'phone' => '064981350',
                'email' => null,
                'type' => 'public',
                'total_students' => null,
                'teacher_name' => null,
                'teacher_email' => null,
                'status' => 'inactive',
            ],
            [
                'name' => 'SM VOKASIONAL KUALA KLAWANG',
                'address' => 'KM. 3, JALAN TITI KUALA KLAWANG 71600',
                'phone' => '066137463',
                'email' => null,
                'type' => 'public',
                'total_students' => null,
                'teacher_name' => null,
                'teacher_email' => null,
                'status' => 'inactive',
            ],
            [
                'name' => 'SBP INTEGRASI JEMPOL',
                'address' => 'KM 1 JALAN BATU KIKIR BATU KIKIR 72200',
                'phone' => '064985978',
                'email' => null,
                'type' => 'public',
                'total_students' => null,
                'teacher_name' => null,
                'teacher_email' => null,
                'status' => 'inactive',
            ],
            // KUALA PILAH schools
            [
                'name' => 'SMK ZABA',
                'address' => 'JALAN TAMPIN KUALA PILAH 72000',
                'phone' => '064811040',
                'email' => null,
                'type' => 'public',
                'total_students' => null,
                'teacher_name' => null,
                'teacher_email' => null,
                'status' => 'inactive',
            ],
            [
                'name' => 'SMK DANGI',
                'address' => 'KM 27, JALAN BAHAU JOHOL 73100',
                'phone' => '064368529',
                'email' => null,
                'type' => 'public',
                'total_students' => null,
                'teacher_name' => null,
                'teacher_email' => null,
                'status' => 'inactive',
            ],
            [
                'name' => 'SMK JUASSEH',
                'address' => 'KM12, JALAN KUALA PILAH BAHAU JUASSEH 72500',
                'phone' => '064983879',
                'email' => null,
                'type' => 'public',
                'total_students' => null,
                'teacher_name' => null,
                'teacher_email' => null,
                'status' => 'inactive',
            ],
            [
                'name' => 'SMK SENALING',
                'address' => 'KM 2 JALAN TAMPIN KUALA PILAH 72000',
                'phone' => '064813171',
                'email' => null,
                'type' => 'public',
                'total_students' => null,
                'teacher_name' => null,
                'teacher_email' => null,
                'status' => 'inactive',
            ],
            [
                'name' => 'SMK JELAI',
                'address' => 'JELAI KUALA PILAH JOHOL 73100',
                'phone' => '064511773',
                'email' => null,
                'type' => 'public',
                'total_students' => null,
                'teacher_name' => null,
                'teacher_email' => null,
                'status' => 'inactive',
            ],
            [
                'name' => 'SMK TUANKU MUHAMMAD',
                'address' => 'KM 2 JALAN TAMPIN KUALA PILAH 72000',
                'phone' => '064811030',
                'email' => null,
                'type' => 'public',
                'total_students' => null,
                'teacher_name' => null,
                'teacher_email' => null,
                'status' => 'inactive',
            ],
            [
                'name' => 'SMK TUNKU KURSHIAH',
                'address' => 'KM2, JLN TAMPIN KUALA PILAH 72000',
                'phone' => '064811123',
                'email' => null,
                'type' => 'public',
                'total_students' => null,
                'teacher_name' => null,
                'teacher_email' => null,
                'status' => 'inactive',
            ],
            [
                'name' => 'SMK CHUNG HUA',
                'address' => 'KM2 JLN TAMPIN, KUALA PILAH 72000',
                'phone' => '064811179',
                'email' => null,
                'type' => 'private',
                'total_students' => null,
                'teacher_name' => null,
                'teacher_email' => null,
                'status' => 'inactive',
            ],
            [
                'name' => 'SMK TUNKU BESAR BURHANUDDIN',
                'address' => 'JALAN KELAB GOLF DIRAJA SERI MENANTI 71550',
                'phone' => '064979005',
                'email' => null,
                'type' => 'public',
                'total_students' => null,
                'teacher_name' => null,
                'teacher_email' => null,
                'status' => 'inactive',
            ],
            [
                'name' => 'SMK DATO\' ABDUL SAMAD',
                'address' => 'KM 30 JALAN SEREMBAN-KUALA PILAH TANJONG IPOH 71500',
                'phone' => '064887252',
                'email' => null,
                'type' => 'public',
                'total_students' => null,
                'teacher_name' => null,
                'teacher_email' => null,
                'status' => 'inactive',
            ],
            [
                'name' => 'SMK DATUK UNDANG ABDUL MANAP',
                'address' => 'KM 3, PEKAN JOHOL 73100',
                'phone' => '064367216',
                'email' => null,
                'type' => 'public',
                'total_students' => null,
                'teacher_name' => null,
                'teacher_email' => null,
                'status' => 'inactive',
            ],
            [
                'name' => 'SEK (SAINS) TUANKU JAAFAR',
                'address' => 'JALAN KAMPUNG GENTAM, KUALA PILAH 72000',
                'phone' => '064811304',
                'email' => null,
                'type' => 'public',
                'total_students' => null,
                'teacher_name' => null,
                'teacher_email' => null,
                'status' => 'inactive',
            ],
            [
                'name' => 'SM RENDAH AGAMA JOHOL',
                'address' => 'KAMPUNG PASIT JLN TAMPIN KUALA PILAH JOHOL 73100',
                'phone' => '064367973',
                'email' => null,
                'type' => 'public',
                'total_students' => null,
                'teacher_name' => null,
                'teacher_email' => null,
                'status' => 'inactive',
            ],
            [
                'name' => 'SM RENDAH AGAMA ULU JEMPOL',
                'address' => 'BATU KIKIR KUALA PILAH 72200',
                'phone' => '064983115',
                'email' => null,
                'type' => 'public',
                'total_students' => null,
                'teacher_name' => null,
                'teacher_email' => null,
                'status' => 'inactive',
            ],
            [
                'name' => 'SM VOKASIONAL JUASSEH',
                'address' => 'JALAN BATU KIKIR, JUASSEH 72500',
                'phone' => '064981572',
                'email' => null,
                'type' => 'public',
                'total_students' => null,
                'teacher_name' => null,
                'teacher_email' => null,
                'status' => 'inactive',
            ],
            // PORT DICKSON schools
            [
                'name' => 'SMK RAJA JUMAAT',
                'address' => 'KM5 JALAN SEREMBAN PORT DICKSON 71007',
                'phone' => '066512022',
                'email' => null,
                'type' => 'public',
                'total_students' => null,
                'teacher_name' => null,
                'teacher_email' => null,
                'status' => 'inactive',
            ],
            [
                'name' => 'SMK DATUK HAJI ABDUL SAMAD',
                'address' => 'BATU 1 1/2, JALAN ESSO PORT DICKSON 71000',
                'phone' => '066471331',
                'email' => null,
                'type' => 'public',
                'total_students' => null,
                'teacher_name' => null,
                'teacher_email' => null,
                'status' => 'inactive',
            ],
            [
                'name' => 'SMK YAM TUAN RADIN',
                'address' => 'KM 11, JALAN SEREMBAN LUKUT 71010',
                'phone' => '066514002',
                'email' => null,
                'type' => 'public',
                'total_students' => null,
                'teacher_name' => null,
                'teacher_email' => null,
                'status' => 'inactive',
            ],
            [
                'name' => 'SMK KAMPUNG BARU SIRUSA',
                'address' => 'KAMPUNG BARU SI RUSA PORT DICKSON 71050',
                'phone' => '066463286',
                'email' => null,
                'type' => 'public',
                'total_students' => null,
                'teacher_name' => null,
                'teacher_email' => null,
                'status' => 'inactive',
            ],
            // Additional PORT DICKSON schools (Batch 2)
            [
                'name' => 'SMK TINGGI PORT DICKSON',
                'address' => 'KM3, JALAN PANTAI, PORT DICKSON 71000',
                'phone' => '066471295',
                'email' => null,
                'type' => 'public',
                'total_students' => null,
                'teacher_name' => null,
                'teacher_email' => null,
                'status' => 'inactive',
            ],
            [
                'name' => 'SMK DATUK MUHAMMAD YUSOF',
                'address' => 'KM2, JALAN SEREMBAN LINGGI 71150',
                'phone' => '066970251',
                'email' => null,
                'type' => 'public',
                'total_students' => null,
                'teacher_name' => null,
                'teacher_email' => null,
                'status' => 'inactive',
            ],
            [
                'name' => 'SMK PASIR PANJANG',
                'address' => 'BT 17, JLN PANTAI PASIR PANJANG 71250',
                'phone' => '0066619027',
                'email' => null,
                'type' => 'public',
                'total_students' => null,
                'teacher_name' => null,
                'teacher_email' => null,
                'status' => 'inactive',
            ],
            [
                'name' => 'SMK TANAH MERAH',
                'address' => 'KM 8, JALAN SEPANG, PORT DICKSON 71960',
                'phone' => '066581570',
                'email' => null,
                'type' => 'public',
                'total_students' => null,
                'teacher_name' => null,
                'teacher_email' => null,
                'status' => 'inactive',
            ],
            [
                'name' => 'SMK BUKIT SAUJANA',
                'address' => 'KM7, JALAN PANTAI, BAGAN PINANG PORT DICKSON 71050',
                'phone' => '066471598',
                'email' => null,
                'type' => 'public',
                'total_students' => null,
                'teacher_name' => null,
                'teacher_email' => null,
                'status' => 'inactive',
            ],
            [
                'name' => 'SM RENDAH AGAMA CHUAH',
                'address' => 'PEKAN CHUAH PORT DICKSON 71960',
                'phone' => '066581701',
                'email' => null,
                'type' => 'public',
                'total_students' => null,
                'teacher_name' => null,
                'teacher_email' => null,
                'status' => 'inactive',
            ],
            [
                'name' => 'SM AGAMA TELOK KEMANG',
                'address' => 'BATU 9 SI RUSA, PORT DICKSON 71050',
                'phone' => '066625366',
                'email' => null,
                'type' => 'public',
                'total_students' => null,
                'teacher_name' => null,
                'teacher_email' => null,
                'status' => 'inactive',
            ],
            [
                'name' => 'SM VOKASIONAL PORT DICKSON',
                'address' => 'KM 5, JALAN SEREMBAN PORT DICKSON 71000',
                'phone' => '066512266',
                'email' => null,
                'type' => 'public',
                'total_students' => null,
                'teacher_name' => null,
                'teacher_email' => null,
                'status' => 'inactive',
            ],
            // REMBAU schools
            [
                'name' => 'SMK DATO\' SEDIA RAJA',
                'address' => 'KM 27 JALAN SEREMBAN TAMPIN REMBAU 71309',
                'phone' => '066851214',
                'email' => null,
                'type' => 'public',
                'total_students' => null,
                'teacher_name' => null,
                'teacher_email' => null,
                'status' => 'inactive',
            ],
            [
                'name' => 'SMK DATO\' UNDANG HAJI ADNAN',
                'address' => 'KM 11, JALAN TAMPIN SEREMBAN, KOTA 71350',
                'phone' => '064384790',
                'email' => null,
                'type' => 'public',
                'total_students' => null,
                'teacher_name' => null,
                'teacher_email' => null,
                'status' => 'inactive',
            ],
            [
                'name' => 'SM SAINS REMBAU',
                'address' => 'PILIN REMBAU 71300',
                'phone' => '066970037',
                'email' => null,
                'type' => 'public',
                'total_students' => null,
                'teacher_name' => null,
                'teacher_email' => null,
                'status' => 'inactive',
            ],
            [
                'name' => 'SEKOLAH MENENGAH KEBANGSAAN PEDAS',
                'address' => 'REMBAU 71400',
                'phone' => '0126368961',
                'email' => null,
                'type' => 'public',
                'total_students' => null,
                'teacher_name' => null,
                'teacher_email' => null,
                'status' => 'inactive',
            ],
            [
                'name' => 'SMK UNDANG REMBAU',
                'address' => 'JALAN MAMPONG REMBAU 71309',
                'phone' => '066851244',
                'email' => null,
                'type' => 'public',
                'total_students' => null,
                'teacher_name' => null,
                'teacher_email' => null,
                'status' => 'inactive',
            ],
            [
                'name' => 'SMK DATUK ABDULLAH',
                'address' => 'ASTANA RAJA, KOTA 71350',
                'phone' => '064382577',
                'email' => null,
                'type' => 'public',
                'total_students' => null,
                'teacher_name' => null,
                'teacher_email' => null,
                'status' => 'inactive',
            ],
            [
                'name' => 'SM AGAMA HAJI MOHD.YATIM',
                'address' => 'KOTA 71350',
                'phone' => '064381411',
                'email' => null,
                'type' => 'public',
                'total_students' => null,
                'teacher_name' => null,
                'teacher_email' => null,
                'status' => 'inactive',
            ],
            [
                'name' => 'SM RENDAH AGAMA REMBAU',
                'address' => 'JALAN DATO\' SEDIA RAJA REMBAU 71300',
                'phone' => '066852404',
                'email' => null,
                'type' => 'public',
                'total_students' => null,
                'teacher_name' => null,
                'teacher_email' => null,
                'status' => 'inactive',
            ],
            [
                'name' => 'SMV DATO\' UNDANG HJ. MUHAMAD SHARIP',
                'address' => 'JALAN DATO\' RAJA MOHD DOM REMBAU 71300',
                'phone' => '066851241',
                'email' => null,
                'type' => 'public',
                'total_students' => null,
                'teacher_name' => null,
                'teacher_email' => null,
                'status' => 'inactive',
            ],
            [
                'name' => 'KOLEJ VOKASIONAL DATO LELA MAHARAJA',
                'address' => 'KM20, JALAN SEREMBAN TAMPIN, CHEMBONG REMBAU 71300',
                'phone' => '066851218',
                'email' => null,
                'type' => 'public',
                'total_students' => null,
                'teacher_name' => null,
                'teacher_email' => null,
                'status' => 'inactive',
            ],
            [
                'name' => 'SMK AGAMA DATO\' HAJI ABU HASSAN HAJI SAIL',
                'address' => 'KILOMETER 1 JALAN SEPERI PEDAS 71400',
                'phone' => '066857162',
                'email' => null,
                'type' => 'public',
                'total_students' => null,
                'teacher_name' => null,
                'teacher_email' => null,
                'status' => 'inactive',
            ],
            // SEREMBAN schools
            [
                'name' => 'SMK TUNKU AMPUAN DURAH',
                'address' => 'JKM 6, JALAN SIKAMAT SEREMBAN 70400',
                'phone' => '067625590',
                'email' => null,
                'type' => 'public',
                'total_students' => null,
                'teacher_name' => null,
                'teacher_email' => null,
                'status' => 'inactive',
            ],
            [
                'name' => 'SMK BUKIT MEWAH',
                'address' => 'JALAN TOK UNGKU SEREMBAN 70100',
                'phone' => '066315922',
                'email' => null,
                'type' => 'public',
                'total_students' => null,
                'teacher_name' => null,
                'teacher_email' => null,
                'status' => 'inactive',
            ],
            [
                'name' => 'SMK DATO\' SHAHARDIN',
                'address' => 'BATU 10, JALAN LABU LABU 71900',
                'phone' => '067911963',
                'email' => null,
                'type' => 'public',
                'total_students' => null,
                'teacher_name' => null,
                'teacher_email' => null,
                'status' => 'inactive',
            ],
            // Additional SEREMBAN schools (Batch 3)
            [
                'name' => 'SMK MAMBAU',
                'address' => 'JALAN PORT DICKSON, KM 12 SEREMBAN 70300',
                'phone' => '066310500',
                'email' => null,
                'type' => 'public',
                'total_students' => null,
                'teacher_name' => null,
                'teacher_email' => null,
                'status' => 'inactive',
            ],
            [
                'name' => 'SMK SENAWANG',
                'address' => 'TAMAN MARIDA SEREMBAN 70450',
                'phone' => '066774946',
                'email' => null,
                'type' => 'public',
                'total_students' => null,
                'teacher_name' => null,
                'teacher_email' => null,
                'status' => 'inactive',
            ],
            [
                'name' => 'SMK DATO\' HAJI MOHD REDZA',
                'address' => 'KM 5, JALAN SIKAMAT SEREMBAN 70400',
                'phone' => '067617281',
                'email' => null,
                'type' => 'public',
                'total_students' => null,
                'teacher_name' => null,
                'teacher_email' => null,
                'status' => 'inactive',
            ],
            [
                'name' => 'SMK PENDETA ZA\'BA',
                'address' => 'TAMAN PAROI JAYA SEREMBAN 70400',
                'phone' => '066785990',
                'email' => null,
                'type' => 'public',
                'total_students' => null,
                'teacher_name' => null,
                'teacher_email' => null,
                'status' => 'inactive',
            ],
            [
                'name' => 'SMK KOMPLEKS KLIA',
                'address' => 'KOMPLEKS KUARTERS KLIA NILAI 71800',
                'phone' => '067917008',
                'email' => null,
                'type' => 'public',
                'total_students' => null,
                'teacher_name' => null,
                'teacher_email' => null,
                'status' => 'inactive',
            ],
            [
                'name' => 'SMK DESA CEMPAKA',
                'address' => 'JLN BBN 6/2C, TMN DESA CEMPAKA, BANDAR BARU NILAI, NILAI 71800',
                'phone' => '067996099',
                'email' => null,
                'type' => 'public',
                'total_students' => null,
                'teacher_name' => null,
                'teacher_email' => null,
                'status' => 'inactive',
            ],
            [
                'name' => 'SMK TAMAN SEMARAK',
                'address' => 'JALAN TS2/1D, TAMAN SEMARAK NILAI 71800',
                'phone' => '067990118',
                'email' => null,
                'type' => 'public',
                'total_students' => null,
                'teacher_name' => null,
                'teacher_email' => null,
                'status' => 'inactive',
            ],
            [
                'name' => 'SMK SERI PAGI',
                'address' => 'TMN SERI PAGI, SENAWANG SEREMBAN 70450',
                'phone' => '066789785',
                'email' => null,
                'type' => 'public',
                'total_students' => null,
                'teacher_name' => null,
                'teacher_email' => null,
                'status' => 'inactive',
            ],
            [
                'name' => 'SMK TAMAN TUANKU JAAFAR',
                'address' => 'SG. GADUT SEREMBAN 71450',
                'phone' => '066774582',
                'email' => null,
                'type' => 'public',
                'total_students' => null,
                'teacher_name' => null,
                'teacher_email' => null,
                'status' => 'inactive',
            ],
            [
                'name' => 'SEK MEN SAINS TUANKU MUNAWIR',
                'address' => 'KM 6, JALAN SIKAMAT, SEREMBAN 70400',
                'phone' => '067630388',
                'email' => null,
                'type' => 'public',
                'total_students' => null,
                'teacher_name' => null,
                'teacher_email' => null,
                'status' => 'inactive',
            ],
            [
                'name' => 'SMK SEREMBAN 2',
                'address' => 'PERSIARAN S2/A4, SEREMBAN 2 SEREMBAN 70300',
                'phone' => '066013644',
                'email' => null,
                'type' => 'public',
                'total_students' => null,
                'teacher_name' => null,
                'teacher_email' => null,
                'status' => 'inactive',
            ],
            [
                'name' => 'SMK PANCHOR',
                'address' => 'JALAN KG. MELAYU PANCHOR SEREMBAN 70400',
                'phone' => '066787433',
                'email' => null,
                'type' => 'public',
                'total_students' => null,
                'teacher_name' => null,
                'teacher_email' => null,
                'status' => 'inactive',
            ],
            [
                'name' => 'SMK SEREMBAN JAYA',
                'address' => 'TAMAN SEREMBAN JAYA SEREMBAN 70450',
                'phone' => '066771260',
                'email' => null,
                'type' => 'public',
                'total_students' => null,
                'teacher_name' => null,
                'teacher_email' => null,
                'status' => 'inactive',
            ],
            [
                'name' => 'SMK BUKIT KEPAYANG',
                'address' => 'GARDEN HOMES, SEREMBAN 2 SEREMBAN 70300',
                'phone' => '066339794',
                'email' => null,
                'type' => 'public',
                'total_students' => null,
                'teacher_name' => null,
                'teacher_email' => null,
                'status' => 'inactive',
            ],
            [
                'name' => 'SMK SEREMBAN JAYA 2',
                'address' => 'TAMAN SEREMBAN JAYA SEREMBAN 70450',
                'phone' => '066753586',
                'email' => null,
                'type' => 'public',
                'total_students' => null,
                'teacher_name' => null,
                'teacher_email' => null,
                'status' => 'inactive',
            ],
            [
                'name' => 'SMK SENAWANG 3',
                'address' => 'TAMAN MARIDA SEREMBAN 70450',
                'phone' => '066778013',
                'email' => null,
                'type' => 'public',
                'total_students' => null,
                'teacher_name' => null,
                'teacher_email' => null,
                'status' => 'inactive',
            ],
            [
                'name' => 'SMK WARISAN PUTERI',
                'address' => 'BANDAR WARISAN PUTERI SEREMBAN 70400',
                'phone' => '067616451',
                'email' => null,
                'type' => 'public',
                'total_students' => null,
                'teacher_name' => null,
                'teacher_email' => null,
                'status' => 'inactive',
            ],
            [
                'name' => 'SMK DATO\' SHAMSUDIN NAIN',
                'address' => 'BATU 13 1/2 JALAN LINSUM RANTAU 71200',
                'phone' => '066941593',
                'email' => null,
                'type' => 'public',
                'total_students' => null,
                'teacher_name' => null,
                'teacher_email' => null,
                'status' => 'inactive',
            ],
            [
                'name' => 'SEKOLAH MENENGAH KEBANGSAAN SEREMBAN 3',
                'address' => 'SEREMBAN 70300',
                'phone' => '0133952949',
                'email' => null,
                'type' => 'public',
                'total_students' => null,
                'teacher_name' => null,
                'teacher_email' => null,
                'status' => 'inactive',
            ],
            [
                'name' => 'SMK KING GEORGE V',
                'address' => 'JLN ZAABA SEREMBAN 70100',
                'phone' => '067623598',
                'email' => null,
                'type' => 'public',
                'total_students' => null,
                'teacher_name' => null,
                'teacher_email' => null,
                'status' => 'inactive',
            ],
            [
                'name' => 'SMK ST PAUL',
                'address' => 'JLN TAN SRI MANICKAVASAGAM SEREMBAN 70200',
                'phone' => '067612931',
                'email' => null,
                'type' => 'public',
                'total_students' => null,
                'teacher_name' => null,
                'teacher_email' => null,
                'status' => 'inactive',
            ],
            [
                'name' => 'SMK METHODIST ACS (M)',
                'address' => 'JALAN LINTANG SEREMBAN 70000',
                'phone' => '067620153',
                'email' => null,
                'type' => 'public',
                'total_students' => null,
                'teacher_name' => null,
                'teacher_email' => null,
                'status' => 'inactive',
            ],
            // Additional SEREMBAN schools (Batch 4)
            [
                'name' => 'SMK PUTERI',
                'address' => 'JALAN LABU LAMA SEREMBAN 70200',
                'phone' => '067655600',
                'email' => null,
                'type' => 'public',
                'total_students' => null,
                'teacher_name' => null,
                'teacher_email' => null,
                'status' => 'inactive',
            ],
            [
                'name' => 'SMK SERI AMPANGAN',
                'address' => 'JALAN KUALA PILAH SEREMBAN 70400',
                'phone' => '067620377',
                'email' => null,
                'type' => 'public',
                'total_students' => null,
                'teacher_name' => null,
                'teacher_email' => null,
                'status' => 'inactive',
            ],
            [
                'name' => 'SMK CHAN WA',
                'address' => '219-220 JALAN TEMIANG SEREMBAN 70200',
                'phone' => '067620144',
                'email' => null,
                'type' => 'public',
                'total_students' => null,
                'teacher_name' => null,
                'teacher_email' => null,
                'status' => 'inactive',
            ],
            [
                'name' => 'SMK TUNKU AMPUAN NAJIHAH',
                'address' => 'JLN HAN HUI FOONG SEREMBAN 70200',
                'phone' => '067622743',
                'email' => null,
                'type' => 'public',
                'total_students' => null,
                'teacher_name' => null,
                'teacher_email' => null,
                'status' => 'inactive',
            ],
            [
                'name' => 'KOLEJ TUNKU KURSHIAH (SMBP)',
                'address' => 'BANDAR ENSTEK SEREMBAN 71760',
                'phone' => '067979800',
                'email' => null,
                'type' => 'public',
                'total_students' => null,
                'teacher_name' => null,
                'teacher_email' => null,
                'status' => 'inactive',
            ],
            [
                'name' => 'SMK DATO SHEIKH AHMAD',
                'address' => 'JALAN TUNKU KURSHIAH SEREMBAN 70400',
                'phone' => '067622278',
                'email' => null,
                'type' => 'public',
                'total_students' => null,
                'teacher_name' => null,
                'teacher_email' => null,
                'status' => 'inactive',
            ],
            [
                'name' => 'SM DATUK ABDUL RAZAK (SMBP)',
                'address' => 'JALAN RANTAU SUNGAI GADUT SEREMBAN 71450',
                'phone' => '066770806',
                'email' => null,
                'type' => 'public',
                'total_students' => null,
                'teacher_name' => null,
                'teacher_email' => null,
                'status' => 'inactive',
            ],
            [
                'name' => 'SMK DATO\' KLANA PUTRA',
                'address' => 'BT 14, JALAN BESAR LENGGENG LENGGENG 71750',
                'phone' => '0387667769',
                'email' => null,
                'type' => 'public',
                'total_students' => null,
                'teacher_name' => null,
                'teacher_email' => null,
                'status' => 'inactive',
            ],
            [
                'name' => 'SMK RANTAU',
                'address' => 'KM 11, JLN LINSUM SEREMBAN 71200',
                'phone' => '066941269',
                'email' => null,
                'type' => 'public',
                'total_students' => null,
                'teacher_name' => null,
                'teacher_email' => null,
                'status' => 'inactive',
            ],
            [
                'name' => 'SMK DATO\' MOHD SAID',
                'address' => 'PEKAN NILAI NILAI 71800',
                'phone' => '067991213',
                'email' => null,
                'type' => 'public',
                'total_students' => null,
                'teacher_name' => null,
                'teacher_email' => null,
                'status' => 'inactive',
            ],
            [
                'name' => 'SMK MANTIN',
                'address' => 'BATU 10, JALAN BESAR MANTIN MANTIN 71700',
                'phone' => '067581251',
                'email' => null,
                'type' => 'public',
                'total_students' => null,
                'teacher_name' => null,
                'teacher_email' => null,
                'status' => 'inactive',
            ],
            [
                'name' => 'SMK (FELDA) SERI SENDAYAN',
                'address' => 'JALAN BESAR, FELDA SENDAYAN SEREMBAN 71950',
                'phone' => '067922569',
                'email' => null,
                'type' => 'public',
                'total_students' => null,
                'teacher_name' => null,
                'teacher_email' => null,
                'status' => 'inactive',
            ],
            [
                'name' => 'SEKOLAH MENENGAH AGAMA RANTAU',
                'address' => 'KUALA SAWAH RANTAU 71200',
                'phone' => '066943626',
                'email' => null,
                'type' => 'public',
                'total_students' => null,
                'teacher_name' => null,
                'teacher_email' => null,
                'status' => 'inactive',
            ],
            [
                'name' => 'SM AGAMA NILAI',
                'address' => 'LOT 7258 NILAI 71800',
                'phone' => '067991826',
                'email' => null,
                'type' => 'public',
                'total_students' => null,
                'teacher_name' => null,
                'teacher_email' => null,
                'status' => 'inactive',
            ],
            [
                'name' => 'SM AGAMA DATO\' KLANA PETRA MAAMOR',
                'address' => 'KM 5, JALAN KUALA PILAH, AMPANGAN, SEREMBAN 70400',
                'phone' => '067639361',
                'email' => null,
                'type' => 'public',
                'total_students' => null,
                'teacher_name' => null,
                'teacher_email' => null,
                'status' => 'inactive',
            ],
            [
                'name' => 'SMV AMPANGAN',
                'address' => 'KM 4 JALAN SEREMBAN-KUALA PILAH, AMPANGAN SEREMBAN 70400',
                'phone' => '067624981',
                'email' => null,
                'type' => 'public',
                'total_students' => null,
                'teacher_name' => null,
                'teacher_email' => null,
                'status' => 'inactive',
            ],
            [
                'name' => 'SMT TUANKU JAAFAR',
                'address' => 'KM 4 JALAN SEREMBAN-KUALA PILAH, AMPANGAN SEREMBAN 70400',
                'phone' => '067638307',
                'email' => null,
                'type' => 'public',
                'total_students' => null,
                'teacher_name' => null,
                'teacher_email' => null,
                'status' => 'inactive',
            ],
            [
                'name' => 'SMKA SHEIKH HJ MOHD SAID',
                'address' => 'JALAN TUNKU KURSHIAH SEREMBAN 70400',
                'phone' => '067623778',
                'email' => null,
                'type' => 'public',
                'total_students' => null,
                'teacher_name' => null,
                'teacher_email' => null,
                'status' => 'inactive',
            ],
            [
                'name' => 'SMA PERSEKUTUAN (SMBP)',
                'address' => 'KM 11, JLN LABU LABU 71900',
                'phone' => '067912245',
                'email' => null,
                'type' => 'public',
                'total_students' => null,
                'teacher_name' => null,
                'teacher_email' => null,
                'status' => 'inactive',
            ],
            // TAMPIN schools
            [
                'name' => 'SMK PASIR BESAR',
                'address' => 'FELDA PASIR BESAR GEMAS 73420',
                'phone' => '064576215',
                'email' => null,
                'type' => 'public',
                'total_students' => null,
                'teacher_name' => null,
                'teacher_email' => null,
                'status' => 'inactive',
            ],
            [
                'name' => 'SMK TUNKU SYED IDRUS',
                'address' => 'KM1, JALAN SEREMBAN TAMPIN 73000',
                'phone' => '064411481',
                'email' => null,
                'type' => 'public',
                'total_students' => null,
                'teacher_name' => null,
                'teacher_email' => null,
                'status' => 'inactive',
            ],
            [
                'name' => 'SMK BUKIT ROKAN',
                'address' => 'FELDA BUKIT ROKAN GEMENCHEH 73200',
                'phone' => '064317700',
                'email' => null,
                'type' => 'public',
                'total_students' => null,
                'teacher_name' => null,
                'teacher_email' => null,
                'status' => 'inactive',
            ],
            // Additional TAMPIN schools (Batch 5)
            [
                'name' => 'SMK GEMAS',
                'address' => 'KM1 JALAN BESAR GEMAS-TAMPIN GEMAS 73400',
                'phone' => '079481608',
                'email' => null,
                'type' => 'public',
                'total_students' => null,
                'teacher_name' => null,
                'teacher_email' => null,
                'status' => 'inactive',
            ],
            [
                'name' => 'SMK JELAI (F)',
                'address' => 'FELDA JELAI GEMAS 73480',
                'phone' => '064347094',
                'email' => null,
                'type' => 'public',
                'total_students' => null,
                'teacher_name' => null,
                'teacher_email' => null,
                'status' => 'inactive',
            ],
            [
                'name' => 'SMK TAMAN INDAH',
                'address' => 'KM 2, JALAN TAMPIN GEMAS TAMPIN 73000',
                'phone' => '064414479',
                'email' => null,
                'type' => 'public',
                'total_students' => null,
                'teacher_name' => null,
                'teacher_email' => null,
                'status' => 'inactive',
            ],
            [
                'name' => 'SMK TUNKU BESAR',
                'address' => 'KM 2 JALAN SEREMBAN TAMPIN 73000',
                'phone' => '064415425',
                'email' => null,
                'type' => 'public',
                'total_students' => null,
                'teacher_name' => null,
                'teacher_email' => null,
                'status' => 'inactive',
            ],
            [
                'name' => 'SMK TUANKU ABDUL RAHMAN',
                'address' => 'JALAN TOK SULONG GEMAS 73400',
                'phone' => '079481055',
                'email' => null,
                'type' => 'public',
                'total_students' => null,
                'teacher_name' => null,
                'teacher_email' => null,
                'status' => 'inactive',
            ],
            [
                'name' => 'SMK BUKIT JALOR',
                'address' => 'JALAN AIR KUNING GEMENCHEH 73200',
                'phone' => '064479305',
                'email' => null,
                'type' => 'public',
                'total_students' => null,
                'teacher_name' => null,
                'teacher_email' => null,
                'status' => 'inactive',
            ],
            [
                'name' => 'SMK DATO\' MOHD TAHA',
                'address' => 'KM 28, JALAN TAMPIN GEMAS GEMENCHEH 73200',
                'phone' => '064316544',
                'email' => null,
                'type' => 'public',
                'total_students' => null,
                'teacher_name' => null,
                'teacher_email' => null,
                'status' => 'inactive',
            ],
            [
                'name' => 'SM RENDAH AGAMA REPAH',
                'address' => 'KM4 JLN TAMPIN-GEMAS TAMPIN 73000',
                'phone' => '064414750',
                'email' => null,
                'type' => 'public',
                'total_students' => null,
                'teacher_name' => null,
                'teacher_email' => null,
                'status' => 'inactive',
            ],
            [
                'name' => 'SM RENDAH AGAMA GEMAS',
                'address' => 'JALAN BATU ANAM GEMAS 73400',
                'phone' => '079482031',
                'email' => null,
                'type' => 'public',
                'total_students' => null,
                'teacher_name' => null,
                'teacher_email' => null,
                'status' => 'inactive',
            ],
        ];

        $insertedCount = 0;
        $skippedCount = 0;

        foreach ($schools as $schoolData) {
            // Check if school with this name already exists
            $existingSchool = School::where('name', $schoolData['name'])->first();
            
            if (!$existingSchool) {
                School::create($schoolData);
                $insertedCount++;
            } else {
                $skippedCount++;
            }
        }

        echo "Successfully processed " . count($schools) . " schools:\n";
        echo "- Inserted: {$insertedCount} new schools\n";
        echo "- Skipped: {$skippedCount} existing schools\n";
    }
}
